package UICiclismo;

import DatosCiclismo.*;
import LogicaCiclismo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Alonso Espinoza Barrantes
 */
public class UICrearCiclista extends javax.swing.JFrame {

    /**
     * 
     */
    private int consecutivoCiclistas;
    
    /**
     * 
     */
    private GestorPrincipal manager;
    
    /**
     * 
     * @param gestor 
     */
    public UICrearCiclista(GestorPrincipal gestor) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.consecutivoCiclistas = 0;
        this.manager = gestor;
    }
    
    /**
     * Valida que los campos digitados por el usuario no esten en blanco y sean correctos
     * @return 
     */
    private boolean validarCiclista(){
        int edad = 0;
        if (this.jTextNombreCiclista.getText().isBlank() || this.jTextApellido1Ciclista.getText().isBlank() || this.jTextApellido2Ciclista.getText().isBlank()){
            return false;
        } else {
            try {
                edad = Integer.parseInt(this.jTextFieldEdadCiclista.getText());
            } catch (NumberFormatException e){
                return false;
            }   
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCiclista = new javax.swing.JPanel();
        jLabelNombreCiclista = new javax.swing.JLabel();
        jTextNombreCiclista = new javax.swing.JTextField();
        jLabel1ApellidoCiclista = new javax.swing.JLabel();
        jLabel2ApellidoCiclista = new javax.swing.JLabel();
        jTextApellido2Ciclista = new javax.swing.JTextField();
        jTextApellido1Ciclista = new javax.swing.JTextField();
        jLabelSexoCiclista = new javax.swing.JLabel();
        jLabelEdadCiclista = new javax.swing.JLabel();
        jComboBoxSexoCiclista = new javax.swing.JComboBox<>();
        jLabelCategoriaCiclista = new javax.swing.JLabel();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        jLabelEspecialidadCiclista = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButtonCrearCiclista = new javax.swing.JButton();
        jTextFieldEdadCiclista = new javax.swing.JTextField();

        setTitle("Crear ciclista");

        jPanelCiclista.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear ciclista"));

        jLabelNombreCiclista.setText("Nombre:");

        jLabel1ApellidoCiclista.setText("1er Apellido:");

        jLabel2ApellidoCiclista.setText("2do Apellido:");

        jLabelSexoCiclista.setText("Sexo:");

        jLabelEdadCiclista.setText("Edad:");

        jComboBoxSexoCiclista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabelCategoriaCiclista.setText("Categoria:");

        jComboBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carretera", "Montaña", "Pista", "BMX" }));

        jLabelEspecialidadCiclista.setText("Especialidad:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amateur", "Profesional", "Veterano" }));

        jButtonCrearCiclista.setText("Aceptar");
        jButtonCrearCiclista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCiclistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCiclistaLayout = new javax.swing.GroupLayout(jPanelCiclista);
        jPanelCiclista.setLayout(jPanelCiclistaLayout);
        jPanelCiclistaLayout.setHorizontalGroup(
            jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiclistaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                        .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                                .addComponent(jLabel1ApellidoCiclista)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiclistaLayout.createSequentialGroup()
                                .addComponent(jLabel2ApellidoCiclista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextApellido2Ciclista, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                                    .addComponent(jLabelEspecialidadCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                                    .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextApellido1Ciclista, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextNombreCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                                            .addComponent(jLabelSexoCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxSexoCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                                            .addComponent(jLabelEdadCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldEdadCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiclistaLayout.createSequentialGroup()
                        .addComponent(jLabelCategoriaCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))))
            .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jButtonCrearCiclista)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCiclistaLayout.setVerticalGroup(
            jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiclistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombreCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexoCiclista)
                    .addComponent(jComboBoxSexoCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreCiclista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEdadCiclista)
                        .addComponent(jTextFieldEdadCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1ApellidoCiclista)
                        .addComponent(jTextApellido1Ciclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2ApellidoCiclista)
                    .addComponent(jTextApellido2Ciclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCiclistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoriaCiclista)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEspecialidadCiclista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCrearCiclista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCiclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearCiclistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCiclistaActionPerformed
        if(this.validarCiclista()){
          consecutivoCiclistas++;
          int edad = Integer.parseInt(this.jTextFieldEdadCiclista.getText());
          int rendimiento = this.manager.generarRendimiento(this.jComboBoxEspecialidad.getSelectedItem().toString(), this.jComboBoxCategoria.getSelectedItem().toString());
          Ciclista ciclista = new Ciclista(consecutivoCiclistas, this.jTextNombreCiclista.getText(), this.jTextApellido1Ciclista.getText(), this.jTextApellido2Ciclista.getText(), edad, this.jComboBoxSexoCiclista.getSelectedItem().toString().charAt(0), this.jComboBoxCategoria.getSelectedItem().toString(), this.jComboBoxEspecialidad.getSelectedItem().toString(), rendimiento);
          this.manager.agregarCiclista(ciclista);
          this.setVisible(false);
          this.jTextNombreCiclista.setText("");
          this.jTextApellido1Ciclista.setText("");
          this.jTextApellido2Ciclista.setText("");
          this.jTextFieldEdadCiclista.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane,"Debe validar que los datos sean correctos y que el formulario este completo.");
        }
    }//GEN-LAST:event_jButtonCrearCiclistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearCiclista;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JComboBox<String> jComboBoxSexoCiclista;
    private javax.swing.JLabel jLabel1ApellidoCiclista;
    private javax.swing.JLabel jLabel2ApellidoCiclista;
    private javax.swing.JLabel jLabelCategoriaCiclista;
    private javax.swing.JLabel jLabelEdadCiclista;
    private javax.swing.JLabel jLabelEspecialidadCiclista;
    private javax.swing.JLabel jLabelNombreCiclista;
    private javax.swing.JLabel jLabelSexoCiclista;
    private javax.swing.JPanel jPanelCiclista;
    private javax.swing.JTextField jTextApellido1Ciclista;
    private javax.swing.JTextField jTextApellido2Ciclista;
    private javax.swing.JTextField jTextFieldEdadCiclista;
    private javax.swing.JTextField jTextNombreCiclista;
    // End of variables declaration//GEN-END:variables
}
