package UICiclismo;

import DatosCiclismo.*;
import LogicaCiclismo.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Alonso Espinoza Barrantes
 */
public class UICrearCarrera extends javax.swing.JFrame {
    /**
     * 
     */
    private int consecutivoCarreras;
    
    /**
     * 
     */
    private GestorPrincipal manager;
    
    /**
     * Creates new form UICrearCarrera
     */
    public UICrearCarrera(GestorPrincipal gestor) {
        initComponents();
        this.setLocationRelativeTo(null);
        consecutivoCarreras = 0;
        this.manager = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipoCarrera = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonCrearCarrera = new javax.swing.JButton();
        jTextFieldDistancia = new javax.swing.JTextField();

        setTitle("Crear carrera");

        jLabel1.setText("Tipo de carrera:");

        jComboBoxTipoCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carretera", "Montaña", "Pista", "BMX" }));

        jLabel2.setText("Distancia:");

        jButtonCrearCarrera.setText("Aceptar");
        jButtonCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTipoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDistancia))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButtonCrearCarrera)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearCarrera)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCarreraActionPerformed
        try{
            int distancia = Integer.parseInt(this.jTextFieldDistancia.getText());
            consecutivoCarreras++;
            if(this.jComboBoxTipoCarrera.getSelectedItem().toString() == "Carretera" || this.jComboBoxTipoCarrera.getSelectedItem().toString() == "Montaña"){
                String pControl = JOptionPane.showInputDialog("Digite los puntos de control de la carrera separados por coma:");
                String[] puntosC = pControl.split(",");
                int puntos = 0;
                ArrayList<Double> puntosControl = new ArrayList();
                for(int i=0; i < puntosC.length; i++){
                    puntosControl.add(Double.parseDouble(puntosC[i]));
                    puntos++;
                }
                Recorrido recorrido = new Recorrido(consecutivoCarreras, this.jComboBoxTipoCarrera.getSelectedItem().toString(), distancia, 0, puntos, puntosControl);
                this.manager.agregarCarrera(recorrido);
            } else {
                String giros = JOptionPane.showInputDialog("Digite la cantidad de vueltas que se deden realizar a la pista/circuito:");
                int cantidadGiros = Integer.parseInt(giros);
                Circuito circuito = new Circuito(consecutivoCarreras, this.jComboBoxTipoCarrera.getSelectedItem().toString(), distancia, 0, cantidadGiros);
                this.manager.agregarCarrera(circuito);
            }
            this.setVisible(false);
            this.jTextFieldDistancia.setText("");
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane,"Debe validar que los datos sean correctos y que el formulario este completo.");
        }
         
    }//GEN-LAST:event_jButtonCrearCarreraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearCarrera;
    private javax.swing.JComboBox<String> jComboBoxTipoCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDistancia;
    // End of variables declaration//GEN-END:variables
}
